apiVersion: v1
appVersion: "1.0"
version: 0.1.0
description: A Helm chart for the Release Engineering team Jenkins master server
name: jenkins-master
icon: http://blog.rackspace.com/wp-content/uploads/2016/03/rs-logo-sm-use-rgb.jpg
sources:
- https://github.com/rcbops/re-jenkins
maintainers:
- name: Hugh Saunders
  email: hugh.saunders@rackspace.com
- name: David Deal
  email: david.deal@rackspace.com
