---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.jenkins.name | quote }}
  labels:
    component: {{ .Values.jenkins.name | quote }}
    context: {{ .Values.global.context | quote }}
    chart: {{ .Chart.Name | quote }}
    version: {{ .Chart.Version | replace "+" "_" | trunc 63  | quote }}
    release: {{ .Release.Name }}
    expose: "public"
spec:
  host: "{{ .Values.jenkins.name }}.devapps.rsi.rackspace.net"
  path: "/"
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.jenkins.name | quote }}
    weight: 1
status:
  ingress: []
