---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ default "jenkins-master" .Values.jenkins.name | quote }}
  labels:
    component: {{ .Values.jenkins.name | quote }}
    context: {{ .Values.global.context | quote }}
    chart: {{ .Chart.Name | quote }}
    version: {{ .Chart.Version | replace "+" "_" | trunc 63  | quote }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ default "jenkins-master" .Values.jenkins.name | quote }}
  replicas: {{ default 1 .Values.jenkins.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.jenkins.name | quote }}
      context: {{ .Values.global.context | quote }}
      chart: {{ .Chart.Name | quote }}
  template:
    metadata:
      name: {{ .Values.jenkins.name | quote }}
      labels:
        component: {{ .Values.jenkins.name | quote }}
        context: {{ .Values.global.context | quote }}
        chart: {{ .Chart.Name | quote }}
      annotations:
    spec:
      imagePullSecrets:
        - name: "docker-registry-deal"
      containers:
        - name: {{ .Values.jenkins.name | quote }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.global.namespace }}/{{ .Values.jenkins.image }}:{{ .Values.jenkins.imageVersion }}"
          imagePullPolicy: {{ .Values.jenkins.pullPolicy | quote }}
          env:
            - name: JENKINS_ARGS
              value: {{ .Values.jenkins.env.jenkinsArgs | quote }}
            - name: JAVA_OPTS
              value: {{ .Values.jenkins.env.javaOpts | quote }}
          ports:
            - containerPort: {{ .Values.jenkins.network.web.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.jenkins.resources.requests.cpu | quote }}
              memory: {{ .Values.jenkins.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.jenkins.resources.limits.cpu | quote }}
              memory: {{ .Values.jenkins.resources.limits.memory | quote }}
          volumeMounts:
            - name: "{{ .Values.jenkins.name }}-vol"
              mountPath: {{ .Values.jenkins.persistence.dir | quote }}
            - name: "{{ .Values.jenkins.name }}-vol-config"
              mountPath: {{ .Values.jenkins.plugin.configDir | quote }}
      volumes:
        - name: "{{ .Values.jenkins.name }}-vol-config"
          configMap:
            name: "{{ .Values.jenkins.name }}-configmap"
      volumeClaimTemplates:
        - "{{ .Values.jenkins.name }}-vol"
