---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.jenkins.name | quote }}
  annotations:
    description: >-
      Keeps track of the '{{ .Values.jenkins.image }}' image changes for the '{{ .Values.jenkins.name }}' application
  labels:
    app.kubernetes.io/name: {{ .Values.jenkins.name | quote }}
    app.kubernetes.io/context: {{ .Values.global.context | quote }}
    app.kubernetes.io/chart: {{ .Chart.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.Version | replace "+" "_" | trunc 63  | quote }}
    app.kubernetes.io/component: {{ .Values.jenkins.name | quote }}
    app.kubernetes.io/part-of: "jenkins"
    app.kubernetes.io/managed-by: "helm"
spec:
#  dockerImageRepository: "{{ .Values.global.imageRegistry }}/{{ .Values.global.namespace }}/{{ .Values.jenkins.image }}"
