{{ if .Values.jenkinsImageSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{.Values.jenkins.name}}-image-secret"
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  secret: {{ .Values.jenkinsImageSecret| b64enc }}
{{- end -}}