---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jenkins.name | quote }}
  labels:
    component: {{ .Values.jenkins.name | quote }}
    context: {{ .Values.global.context | quote }}
    chart: {{ .Chart.Name | quote }}
    version: {{ .Chart.Version | replace "+" "_" | trunc 63  | quote }}
spec:
  type: NodePort
  selector:
    component: {{ .Values.jenkins.name | quote }}
    context: {{ .Values.global.context | quote }}
    chart: {{ .Chart.Name | quote }}
  ports:
  - port: {{ .Values.jenkins.network.port }}
    name: {{ .Values.jenkins.network.protocol | quote }}
    targetPort: {{ .Values.jenkins.network.targetPort }}
#  externalIPs:
#    - 192.168.99.100
