---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.jenkins.name }}-configmap"
  labels:
    component: {{ .Values.jenkins.name | quote }}
    context: {{ .Values.global.context | quote }}
    chart: {{ .Chart.Name | quote }}
    version: {{ .Chart.Version | replace "+" "_" | trunc 63  | quote }}
    release: {{ .Release.Name }}
data:
  github-plugin-configuration.xml: |-
    <?xml version='1.1' encoding='UTF-8'?>
    <github-plugin-configuration plugin="github@1.28.1">
      <configs>
        <github-server-config>
          <apiUrl>{{ .Values.jenkins.plugin.github.server.apiUrl }}</apiUrl>
          <manageHooks>{{ .Values.jenkins.plugin.github.server.manageHooks }}</manageHooks>
          <credentialsId>{{ .Values.jenkins.plugin.github.server.credentialsId }}</credentialsId>
          <clientCacheSize>{{ .Values.jenkins.plugin.github.server.clientCacheSize }}</clientCacheSize>
        </github-server-config>
      </configs>
      <hookSecretConfig>
        <credentialsId>{{ .Values.jenkins.plugin.github.hookSecretConfig.credentialsId }}</credentialsId>
      </hookSecretConfig>
    </github-plugin-configuration>
  jenkins.model.JenkinsLocationConfiguration.xml: |-
    <?xml version='1.1' encoding='UTF-8'?>
    <jenkins.model.JenkinsLocationConfiguration>
      <adminAddress>{{ .Values.jenkins.plugin.jenkinsLocation.adminAddress }}</adminAddress>
      <jenkinsUrl>{{ .Values.jenkins.plugin.jenkinsLocation.jenkinsUrl }}</jenkinsUrl>
    </jenkins.model.JenkinsLocationConfiguration>
