---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.jenkins.name | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.jenkins.name | quote }}
    app.kubernetes.io/context: {{ .Values.global.context | quote }}
    app.kubernetes.io/chart: {{ .Chart.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.Version | replace "+" "_" | trunc 63  | quote }}
    app.kubernetes.io/component: {{ .Values.jenkins.name | quote }}
    app.kubernetes.io/part-of: "jenkins"
    app.kubernetes.io/managed-by: "helm"
    expose: "public"
spec:
  host: "{{ .Values.jenkins.name }}.devapps.rsi.rackspace.net"
  path: "/"
  port:
    targetPort: {{ .Values.jenkins.network.web.port }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.jenkins.name | quote }}
    weight: 1
status:
  ingress: []
