{{ if .Values.jenkinsImageSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{.Values.jenkins.name}}-image-secret"
  labels:
    app.kubernetes.io/name: {{ .Values.jenkins.name | quote }}
    app.kubernetes.io/context: {{ .Values.global.context | quote }}
    app.kubernetes.io/chart: {{ .Chart.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.Version | replace "+" "_" | trunc 63  | quote }}
    app.kubernetes.io/component: {{ .Values.jenkins.name | quote }}
    app.kubernetes.io/part-of: "jenkins"
    app.kubernetes.io/managed-by: "helm"
type: Opaque
data:
  secret: {{ .Values.jenkinsImageSecret | b64enc }}
{{- end -}}
