---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jenkins.name | quote }}
  labels:
    component: {{ .Values.jenkins.name | quote }}
    context: {{ .Values.global.context | quote }}
    chart: {{ .Chart.Name | quote }}
    version: {{ .Chart.Version | replace "+" "_" | trunc 63  | quote }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    component: {{ .Values.jenkins.name | quote }}
    context: {{ .Values.global.context | quote }}
    chart: {{ .Chart.Name | quote }}
  ports:
    - name: web
      port: {{ .Values.jenkins.network.web.port }}
      targetPort: {{ .Values.jenkins.network.web.targetPort }}
    - name: slave
      port: {{ .Values.jenkins.network.slave.port }}
      targetPort: {{ .Values.jenkins.network.slave.targetPort }}
