---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.jenkins.name | quote }}
  annotations:
    description: >-
      Keeps track of the '{{ .Values.jenkins.image }}' image changes for the '{{ .Values.jenkins.name }}' application
  labels:
    component: {{ .Values.jenkins.name | quote }}
    context: {{ .Values.global.context | quote }}
    chart: {{ .Chart.Name | quote }}
    version: {{ .Chart.Version | replace "+" "_" | trunc 63 | quote }}
    release: {{ .Release.Name }}
spec:
  dockerImageRepository: "{{ .Values.global.imageRegistry }}/{{ .Values.global.namespace }}/{{ .Values.jenkins.image }}"