---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jenkins.name | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.jenkins.name | quote }}
    app.kubernetes.io/context: {{ .Values.global.context | quote }}
    app.kubernetes.io/chart: {{ .Chart.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.Version | replace "+" "_" | trunc 63  | quote }}
    app.kubernetes.io/component: {{ .Values.jenkins.name | quote }}
    app.kubernetes.io/part-of: "jenkins"
    app.kubernetes.io/managed-by: "helm"
spec:
  type: NodePort
  selector:
    component: {{ .Values.jenkins.name | quote }}
    context: {{ .Values.global.context | quote }}
    chart: {{ .Chart.Name | quote }}
  ports:
    - name: web
      port: {{ .Values.jenkins.network.web.port }}
      targetPort: {{ .Values.jenkins.network.web.targetPort }}
    - name: slave
      port: {{ .Values.jenkins.network.slave.port }}
      targetPort: {{ .Values.jenkins.network.slave.targetPort }}
